name: Trigger auto deployment for mhr-ntu-knowledge-share-uks-aks

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/mhr-ntu-knowledge-share-uks-aks-AutoDeployTrigger.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mhrntuknowledgeshareuksacr.azurecr.io
          username: ${{ secrets.MHRNTUKNOWLEDGESHAREUKSAKS_REGISTRY_USERNAME }}
          password: ${{ secrets.MHRNTUKNOWLEDGESHAREUKSAKS_REGISTRY_PASSWORD }}
          
      - name: Build and push container image to registry
        run: |
          docker build "$GITHUB_WORKSPACE/src/KnowledgeShare" -f "src/KnowledgeShare/Dockerfile" -t mhrntuknowledgeshareuksacr.azurecr.io/mhr-ntu-knowledge-share-uks-aks:${{ github.sha }}
          docker push mhrntuknowledgeshareuksacr.azurecr.io/mhr-ntu-knowledge-share-uks-aks:${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MHRNTUKNOWLEDGESHAREUKSAKS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mhr-ntu-knowledge-share-uks-aks -g mhr-ntu-knowledge-share-uks-rg --server mhrntuknowledgeshareuksacr.azurecr.io --username  ${{ secrets.MHRNTUKNOWLEDGESHAREUKSAKS_REGISTRY_USERNAME }} --password ${{ secrets.MHRNTUKNOWLEDGESHAREUKSAKS_REGISTRY_PASSWORD }}
            az containerapp update -n mhr-ntu-knowledge-share-uks-aks -g mhr-ntu-knowledge-share-uks-rg --image mhrntuknowledgeshareuksacr.azurecr.io/mhr-ntu-knowledge-share-uks-aks:${{ github.sha }}
